version: '3'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/pgsql/data
        volumes:
            - ./data:/var/lib/pgsql/data
        ports: # @FollowUp: This might not be needed... (this just exposes the port to the host machine)
            - "5432:5432"

    webserver:
        image: af-dev:latest
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/webserver:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: af-dev:latest
        restart: always
        depends_on:
            - redis
        environment:
            - EXECUTOR=Celery
        volumes:
            - ./logs/flower:/usr/local/airflow/logs
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: af-dev:latest
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/scheduler:/usr/local/airflow/logs
        environment:
            - LOAD_EX=n
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: af-dev:latest
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/worker:/usr/local/airflow/logs
        environment:
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker

