version: '3'
services:
    redis:
        image: 'redis:3.2.7'

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/pgsql/data
        volumes:
            - ./pgsql_data:/var/lib/pgsql/data
        ports:
            - "5432:5432"

    webserver:
        image: af-dev:{tag} # Should be able to have some tagging options whne deploying?
        restart: always
        depends_on:
            - postgres
            - redis
        environment:
            - LOAD_EX=n
            - AIRFLOW_HOME=/usr/local/airflow
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/webserver:/usr/local/airflow/logs
            - {airflow_source_path}:/usr/local/airflow/code
            - ./scripts:/usr/local/airflow/scripts
            - ./config:/usr/local/airflow/config
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

    flower:
        image: af-dev:{tag}
        restart: always
        depends_on:
            - redis
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
            - EXECUTOR=Celery
        volumes:
            - ./logs/flower:/usr/local/airflow/logs
            - {airflow_source_path}:/usr/local/airflow/code
            - ./scripts:/usr/local/airflow/scripts
            - ./config:/usr/local/airflow/config
        ports:
            - "5555:5555"
        command: flower

    scheduler:
        image: af-dev:{tag}
        restart: always
        depends_on:
            - webserver
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/scheduler:/usr/local/airflow/logs
            - {airflow_source_path}:/usr/local/airflow/code
            - ./scripts:/usr/local/airflow/scripts
            - ./config:/usr/local/airflow/config
        environment:
            - LOAD_EX=n
            - AIRFLOW_HOME=/usr/local/airflow
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: scheduler

    worker:
        image: af-dev:{tag}
        restart: always
        depends_on:
            - scheduler
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/worker:/usr/local/airflow/logs
            - {airflow_source_path}:/usr/local/airflow/code
            - ./scripts:/usr/local/airflow/scripts
            - ./config:/usr/local/airflow/config
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
            - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
            - EXECUTOR=Celery
        command: worker

