version: "3"
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
            - PGDATA=/var/lib/pgsql/data
        volumes:
            - ./{pgsql_data_location}:/var/lib/pgsql/data
        ports: # @FollowUp: This might not be needed... (this just exposes the port to the host machine)
            - "5432:5432"

    cli:
        image: af-dev:{tag}
        depends_on:
            - postgres
        environment:
            - AIRFLOW_HOME=/usr/local/airflow
        volumes:
            - ./dags:/usr/local/airflow/dags
            - ./logs/cli:/usr/local/airflow/logs
            - {airflow_source_path}:/usr/local/airflow/code
            - ./scripts:/usr/local/airflow/scripts
            - ./config:/usr/local/airflow/config
        entrypoint: /bin/bash
        #user: root # @Question: should cli as root be optional here?

